[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
lib_ldf_mode = chain+    ; Forces PlatformIO to evaluate C++ macros
lib_deps = 
    https://github.com/Seeed-Studio/Seeed_GFX.git ; Or your exact git URL
build_flags =
    -I include