
#include "fonts/BeauRivage_Regular24pt7b.h"
#include "fonts/BeauRivage_Regular32pt7b.h"
#include "fonts/PlayfairDisplay_VariableFont_wght18pt7b.h"
#include "fonts/PlayfairDisplay_VariableFont_wght24pt7b.h"
#include "fonts/PlayfairDisplay_VariableFont_wght32pt7b.h"
#include "fonts/InterTight_VariableFont_wght12pt7b.h"
#include "fonts/InterTight_VariableFont_wght18pt7b.h"
#include "fonts/InterTight_VariableFont_wght24pt7b.h"
#include "fonts/InterTight_VariableFont_wght32pt7b.h"